USE [master]
GO
/****** Object:  Database [Blazor_TodoDb]    Script Date: 4/14/2020 11:36:57 AM ******/
CREATE DATABASE [Blazor_TodoDb]
 GO
ALTER DATABASE [Blazor_TodoDb] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Blazor_TodoDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Blazor_TodoDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Blazor_TodoDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Blazor_TodoDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Blazor_TodoDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Blazor_TodoDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Blazor_TodoDb] SET  MULTI_USER 
GO
ALTER DATABASE [Blazor_TodoDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Blazor_TodoDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Blazor_TodoDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Blazor_TodoDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [Blazor_TodoDb]
GO
/****** Object:  Table [dbo].[ToDo]    Script Date: 4/14/2020 11:36:57 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ToDo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Task] [nvarchar](100) NOT NULL,
	[Status] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Blazor_TodoDb] SET  READ_WRITE 
GO
